site_name: Poradnik Statystyka Excel
nav:
  - Strona główna: index.md
  - Miary tendencji centralnej: tendencja.md
  - Miary rozproszenia: rozproszenie.md
  - Korelacje i współczynniki: korelacje.md
  - Analiza regresji: regresja.md
  - Inne funkcje: inne_funkcje.md
  - Testy statystyczne: testy.md
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: '(prefers-color-scheme: light)'
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: '(prefers-color-scheme: dark)'

extra_css:
  - assets/css/custom.css

